language: node_js
node_js:
  - node
script: npm test
deploy:
  provider: script
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm run release
  skip_cleanup: true
  on:
    branch: master